# Generated by Django 5.0.2 on 2024-11-05 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_entitytype_entity_description_entity_parent_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.stage'),
        ),
        migrations.AlterField(
            model_name='document',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.stage'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
